# Generated by Django 5.1.3 on 2024-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('genre', models.CharField(blank=True, max_length=200, verbose_name='Жанр книги')),
                ('publisher', models.CharField(max_length=200, verbose_name='Издательство')),
                ('year', models.CharField(max_length=4, verbose_name='Год издательства')),
                ('author', models.CharField(default='Нет автора', max_length=100, verbose_name='Автор книги')),
                ('description', models.TextField(max_length=2000, verbose_name='Аннотация книги')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN  книги')),
                ('price', models.CharField(max_length=10, verbose_name='Цена (руб.)')),
                ('photo', models.ImageField(upload_to='Website/parcer/images/', verbose_name='Изображение обложки')),
            ],
        ),
    ]
